apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-script
data:
  user.sql: |
    CREATE DATABASE IF NOT EXISTS petclinic;

    GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'localhost' IDENTIFIED BY 'petclinic';
